#!/bin/bash
#
#SBATCH -J testGAN
#SBATCH -p cfdg.p
#SBATCH --mem-per-cpu 5000       # 2.3 GB Memory per Task 
#SBATCH -t 1-00:00           # time (D-HH:MM) 
#SBATCH -o logs/test/log_test.%N.%j.out  # STDOUT 
#SBATCH -e logs/test/log_test.%N.%j.err  # STDERR 
#SBATCH --ntasks 1                # Number of Tasks
#SBATCH --cpus-per-task 24        # CPU's per Task
#SBATCH --exclusive
#SBATCH --gres=gpu:1

module load hpc-env/8.3
module load TensorFlow/1.13.1-fosscuda-2019b-Python-3.7.4

#GB
#python3 /gss/work/dahl0071/thesis/phire2/test.py --log "final/log_tensorflow.cfdg003.24629762.out" --model_name "wind-20220524-135041" --test_dir "/nfs/data/dahl0071/thesis/data/test/GB/final/*/" --dom ""GB"
#python3 /gss/work/dahl0071/thesis/phire2/test.py --log "final/log_tensorflow.cfdg001.24645765.out" --model_name "wind-20220527-191118" --test_dir "/nfs/data/dahl0071/thesis/data/test/GB/final/*/" --dom "GB"
#python3 /gss/work/dahl0071/thesis/phire2/test.py --log "WGAN/log_tensorflow.cfdg001.24695524.out" --model_name "wind-20220602-122733" --test_dir "/nfs/data/dahl0071/thesis/data/test/GB/final/*/" --dom "GB"
#python3 /gss/work/dahl0071/thesis/phire2/test.py --log "WGAN/log_tensorflow.cfdg002.24698819.out" --model_name "wind-20220603-122238" --test_dir "/nfs/data/dahl0071/thesis/data/test/GB/final/*/" --dom "GB"
python3 /gss/work/dahl0071/thesis/phire2/test.py --log "WGAN/log_tensorflow.cfdg001.24765441.out" --model_name "wind-20220618-010116" --test_dir "/nfs/data/dahl0071/thesis/data/test/CE/stoch" --dom "CE"

python3 /gss/work/dahl0071/thesis/phire2/test.py --log "WGAN/log_tensorflow.cfdg001.24765441.out" --model_name "wind-20220618-010116" --test_dir "/nfs/data/dahl0071/thesis/data/test/GB/stoch" --dom "GB"


#python3 /gss/work/dahl0071/thesis/phire2/test.py --log "final/log_tensorflow.cfdg002.24647834.out" --model_name "wind-20220528-031534" --test_dir "/nfs/data/dahl0071/thesis/data/test/CE/final/*/" --dom "CE"


#python3 /gss/work/dahl0071/thesis/phire2/test.py --log "WGAN/log_tensorflow.cfdg001.24655437.out" --model_name "wind-20220531-204547" --test_dir "/nfs/data/dahl0071/thesis/data/test/GB/final/*/"


#CE
#python3 /gss/work/dahl0071/thesis/phire2/test.py --log "WGAN/log_tensorflow.cfdg001.24655437.out" --model_name "wind-20220531-204547" --test_dir "/nfs/data/dahl0071/thesis/data/test/CE/final/*/"
