#!/bin/bash
#
#SBATCH -J tf_training
#SBATCH -p cfdg.p
#SBATCH --mem-per-cpu 5000       # 2.3 GB Memory per Task 
#SBATCH -t 3-00:00           # time (D-HH:MM) 
#SBATCH -o logs/CV/log_tensorflow.%N.%j.out  # STDOUT 
#SBATCH -e logs/CV/log_tensorflow.%N.%j.err  # STDERR 
#SBATCH --ntasks 1                # Number of Tasks
#SBATCH --cpus-per-task 24        # CPU's per Task
#SBATCH --exclusive
#SBATCH --gres=gpu:1

module load hpc-env/8.3
module load TensorFlow/1.13.1-fosscuda-2019b-Python-3.7.4


python3 /gss/work/dahl0071/thesis/phire2/main.py --isCNN --train_dir "/nfs/data/dahl0071/thesis/data/train/CE/CV1/*/" --test_dir "/nfs/data/dahl0071/thesis/data/test/CE/CV1/*/"  --valid_dir "/nfs/data/dahl0071/thesis/data/valid/CE/CV1/*/" --ne 200 --bs 100

#--HR_static_path /nfs/data/dahl0071/thesis/data/static/CE/HR.npy #--use_mod_gen
#--LR_static_path /nfs/data/dahl0071/thesis/data/static/CE/LR.npy --HR_static_path /nfs/data/dahl0071/thesis/data/static/CE/HR.npy  
