#!/bin/bash
#
#SBATCH -J tf_training
#SBATCH -p cfdg.p
#SBATCH --mem-per-cpu 5000       # 2.3 GB Memory per Task 
#SBATCH -t 2-00:00           # time (D-HH:MM) 
#SBATCH -o logs/GB/log_tensorflow.%N.%j.out  # STDOUT 
#SBATCH -e logs/GB/log_tensorflow.%N.%j.err  # STDERR 
#SBATCH --ntasks 1                # Number of Tasks
#SBATCH --cpus-per-task 24        # CPU's per Task
#SBATCH --exclusive
#SBATCH --gres=gpu:1

module load hpc-env/8.3
module load TensorFlow/1.13.1-fosscuda-2019b-Python-3.7.4

python3 /gss/work/dahl0071/thesis/phire2/main.py --train_dir "/nfs/data/dahl0071/thesis/data/train/GB/final/*" --test_dir "/nfs/data/dahl0071/thesis/data/test/GB/final/*"  --valid_dir "/nfs/data/dahl0071/thesis/data/valid/GB/2017" --ne 200 --epoch_shift 400 --model_path "/gss/work/dahl0071/thesis/models/wind-20220527-191118/cnn/cnn" --bs 128 --HR_static_path "/nfs/data/dahl0071/thesis/data/static/GB/HR.npy" 
#--LR_static_path /nfs/data/dahl0071/thesis/data/static/CE/LR.npy #--use_mod_gen
#--LR_static_path /nfs/data/dahl0071/thesis/data/static/CE/LR.npy --HR_static_path /nfs/data/dahl0071/thesis/data/static/CE/HR.npy  
